# Generated by Django 4.1.7 on 2023-04-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_course_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ManyToManyField(blank=True, null=True, to='reviews.professor'),
        ),
    ]
