# Generated by Django 4.1.7 on 2023-04-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_available_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_courses',
            name='name_slug',
            field=models.SlugField(null=True),
        ),
    ]
