# Generated by Django 4.1.7 on 2023-04-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_available_courses_name_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='no_of_people_reviewed',
            field=models.IntegerField(null=True),
        ),
    ]
