# Generated by Django 4.1.7 on 2023-04-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_course_no_of_people_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='full_name_with_space_first_letter_capital_for_all_words',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='full_name_with_space_lowercase',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='full_name_with_space_uppercase',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='short_form_capital',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='short_form_small',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
